services:
  redis:
    image: redis:latest
    command: >
      redis-server
      --save 20 1
      --requirepass ${DATABASE_PASSWORD}
      --tcp-keepalive 60
      --timeout 0
    volumes:
      - redis:/data
    restart: always
  scholarsome:
#    image: hwgilbert16/scholarsome:latest
    image: scholarsome-kevin:1.01
    platform: "linux/amd64"
    # network_mode: host
    ports:
       - "${HTTP_PORT}:${HTTP_PORT}"
#      - "(your ssl port):8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "NODE_ENV=${NODE_ENV}"
      - "DATABASE_URL=mysql://${SQL_USER}:${SQL_PASSWORD}@10.0.0.1:3306/flashcard"
      - "JWT_SECRET=${JWT_SECRET}"
      - "HTTP_PORT=${HTTP_PORT}"
      - "STORAGE_TYPE=${STORAGE_TYPE}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_USERNAME="
      - "REDIS_PASSWORD=${DATABASE_PASSWORD}"
      - "STORAGE_LOCAL_DIR=/data"
      - "S3_STORAGE_ENDPOINT=${S3_STORAGE_ENDPOINT}"
      - "S3_STORAGE_ACCESS_KEY=${S3_STORAGE_ACCESS_KEY}"
      - "S3_STORAGE_SECRET_KEY=${S3_STORAGE_SECRET_KEY}"
      - "S3_STORAGE_REGION=${S3_STORAGE_REGION}"
      - "S3_STORAGE_BUCKET=${S3_STORAGE_BUCKET}"
      - "SMTP_HOST=${SMTP_HOST}"
      - "SMTP_PORT=${SMTP_PORT}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
      - "HOST=${HOST}"
      - "SSL_KEY_BASE64=${SSL_KEY_BASE64}"
      - "SSL_CERT_BASE64=${SSL_CERT_BASE64}"
      - "SCHOLARSOME_RECAPTCHA_SITE=${RECAPTCHA_SITE}"
      - "SCHOLARSOME_RECAPTCHA_SECRET=${RECAPTCHA_SECRET}"
    volumes:
      - scholarsome:/data
    depends_on:
      - redis
    restart: always
volumes:
  redis:
    driver: local
  scholarsome: